### ISSUE TITLE
User can search for a player by username.

### ISSUE THREAD

**Issue by peterhermansen** [hermansenph/rocket-league-stats#2]
# Motivation
User can search & see all their stats on one page. User can look up stats of others.

- [x] Create Wireframe

- [x] Add search bar to top of page

- [x] Add search function that returns user data

- [x] Add function to remove leaderboard if search function is used

- [x] Add function to write that user data to the page

![screen shot 2017-09-13 at 1 21 29 pm](https://user-images.githubusercontent.com/31448931/30398792-868b1274-9886-11e7-8fc8-fc814c2d194d.png)

**Comment by thebearingedge** [comment]
I recommend a "table" view for player details.

| Stat | Score |
| ---- | ------ |
| Wins | 1000 |
| Goals | 2000 |
| etc... | etc... |
